import os
env = Environment(ENV = os.environ)



# How to build the diam vs spd diagram:
env.Command("tmp/Q1_PropSpdResults.txt", ["Q1_GenerateResults.py","Model4_Q1.hoc.tmpl"] , "python Q1_GenerateResults.py")
q1 = env.Command("images/fig1_diameter_propvelocity.pdf", ["Q1_GenerateGraphs.py","tmp/Q1_PropSpdResults.txt"], "python Q1_GenerateGraphs.py")


# How to build the sample voltage trace diagram:
env.Command("tmp/Q2_VoltageTraces.txt", ["Model4_Q2.hoc"] , "nrngui Model4_Q2.hoc")
q2 = env.Command("images/fig2_sample_traces.pdf", ["Q2_GenerateGraphs.py","tmp/Q2_VoltageTraces.txt"], "python Q2_GenerateGraphs.py")



# How to build the pdf:
pdf = env.PDF("tex/writeup.tex")
env.Depends(pdf, [q1,q2])
